services:
  app:
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "80:80"
    expose:
      - "80"
    environment:
      DOMAIN: ${APP_URL}
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "true"
      ADMIN_TOKEN: ${ADMIN_PASSWORD}
      WEBSOCKET_ENABLED: "true"
      IP_HEADER: X-Real-IP
      LOG_LEVEL: warn
    volumes:
      - vaultwarden-data:/data

volumes:
  vaultwarden-data:
